# Generated by Django 4.1 on 2022-08-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('numNotes', models.FloatField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='numNotes',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
