# Generated by Django 4.1 on 2022-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_note_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pdf',
            field=models.FileField(default='../media/test.pdf', upload_to='uploads'),
        ),
    ]
