# Generated by Django 4.1 on 2022-08-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_alter_note_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(default='AA', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='format',
            field=models.CharField(choices=[('TYPED', 'typed'), ('HANDWRITTEN', 'handwritten'), ('UNSPECIFIED', 'unspecified')], default='unspecified', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='numVotes',
            field=models.FloatField(default=0),
        ),
    ]
